/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CliRouteImport } from './routes/cli'
import { Route as DualWorldRulesRouteImport } from './routes/dual-world-rules'
import { Route as DualWorldsRouteImport } from './routes/dual-worlds'
import { Route as FromJavascriptRouteImport } from './routes/from-javascript'
import { Route as FromSystemsRouteImport } from './routes/from-systems'
import { Route as HostIoRouteImport } from './routes/host-io'
import { Route as InstallRouteImport } from './routes/install'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as NativeTypesRouteImport } from './routes/native-types'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as ReferenceHostIoRouteImport } from './routes/reference-host-io'
import { Route as ReferencePackagesRouteImport } from './routes/reference-packages'
import { Route as TypesRouteImport } from './routes/types'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const DualWorldRulesRoute = DualWorldRulesRouteImport.update({
  id: '/dual-world-rules',
  path: '/dual-world-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const DualWorldsRoute = DualWorldsRouteImport.update({
  id: '/dual-worlds',
  path: '/dual-worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const FromJavascriptRoute = FromJavascriptRouteImport.update({
  id: '/from-javascript',
  path: '/from-javascript',
  getParentRoute: () => rootRouteImport,
} as any)
const FromSystemsRoute = FromSystemsRouteImport.update({
  id: '/from-systems',
  path: '/from-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIoRoute = HostIoRouteImport.update({
  id: '/host-io',
  path: '/host-io',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const NativeTypesRoute = NativeTypesRouteImport.update({
  id: '/native-types',
  path: '/native-types',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceHostIoRoute = ReferenceHostIoRouteImport.update({
  id: '/reference-host-io',
  path: '/reference-host-io',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencePackagesRoute = ReferencePackagesRouteImport.update({
  id: '/reference-packages',
  path: '/reference-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesRoute = TypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/dual-world-rules': typeof DualWorldRulesRoute
  '/dual-worlds': typeof DualWorldsRoute
  '/from-javascript': typeof FromJavascriptRoute
  '/from-systems': typeof FromSystemsRoute
  '/host-io': typeof HostIoRoute
  '/install': typeof InstallRoute
  '/learn': typeof LearnRoute
  '/modules': typeof ModulesRoute
  '/native-types': typeof NativeTypesRoute
  '/packages': typeof PackagesRoute
  '/reference': typeof ReferenceRoute
  '/reference-host-io': typeof ReferenceHostIoRoute
  '/reference-packages': typeof ReferencePackagesRoute
  '/types': typeof TypesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/dual-world-rules': typeof DualWorldRulesRoute
  '/dual-worlds': typeof DualWorldsRoute
  '/from-javascript': typeof FromJavascriptRoute
  '/from-systems': typeof FromSystemsRoute
  '/host-io': typeof HostIoRoute
  '/install': typeof InstallRoute
  '/learn': typeof LearnRoute
  '/modules': typeof ModulesRoute
  '/native-types': typeof NativeTypesRoute
  '/packages': typeof PackagesRoute
  '/reference': typeof ReferenceRoute
  '/reference-host-io': typeof ReferenceHostIoRoute
  '/reference-packages': typeof ReferencePackagesRoute
  '/types': typeof TypesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/dual-world-rules': typeof DualWorldRulesRoute
  '/dual-worlds': typeof DualWorldsRoute
  '/from-javascript': typeof FromJavascriptRoute
  '/from-systems': typeof FromSystemsRoute
  '/host-io': typeof HostIoRoute
  '/install': typeof InstallRoute
  '/learn': typeof LearnRoute
  '/modules': typeof ModulesRoute
  '/native-types': typeof NativeTypesRoute
  '/packages': typeof PackagesRoute
  '/reference': typeof ReferenceRoute
  '/reference-host-io': typeof ReferenceHostIoRoute
  '/reference-packages': typeof ReferencePackagesRoute
  '/types': typeof TypesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli'
    | '/dual-world-rules'
    | '/dual-worlds'
    | '/from-javascript'
    | '/from-systems'
    | '/host-io'
    | '/install'
    | '/learn'
    | '/modules'
    | '/native-types'
    | '/packages'
    | '/reference'
    | '/reference-host-io'
    | '/reference-packages'
    | '/types'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cli'
    | '/dual-world-rules'
    | '/dual-worlds'
    | '/from-javascript'
    | '/from-systems'
    | '/host-io'
    | '/install'
    | '/learn'
    | '/modules'
    | '/native-types'
    | '/packages'
    | '/reference'
    | '/reference-host-io'
    | '/reference-packages'
    | '/types'
  id:
    | '__root__'
    | '/'
    | '/cli'
    | '/dual-world-rules'
    | '/dual-worlds'
    | '/from-javascript'
    | '/from-systems'
    | '/host-io'
    | '/install'
    | '/learn'
    | '/modules'
    | '/native-types'
    | '/packages'
    | '/reference'
    | '/reference-host-io'
    | '/reference-packages'
    | '/types'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliRoute: typeof CliRoute
  DualWorldRulesRoute: typeof DualWorldRulesRoute
  DualWorldsRoute: typeof DualWorldsRoute
  FromJavascriptRoute: typeof FromJavascriptRoute
  FromSystemsRoute: typeof FromSystemsRoute
  HostIoRoute: typeof HostIoRoute
  InstallRoute: typeof InstallRoute
  LearnRoute: typeof LearnRoute
  ModulesRoute: typeof ModulesRoute
  NativeTypesRoute: typeof NativeTypesRoute
  PackagesRoute: typeof PackagesRoute
  ReferenceRoute: typeof ReferenceRoute
  ReferenceHostIoRoute: typeof ReferenceHostIoRoute
  ReferencePackagesRoute: typeof ReferencePackagesRoute
  TypesRoute: typeof TypesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dual-world-rules': {
      id: '/dual-world-rules'
      path: '/dual-world-rules'
      fullPath: '/dual-world-rules'
      preLoaderRoute: typeof DualWorldRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dual-worlds': {
      id: '/dual-worlds'
      path: '/dual-worlds'
      fullPath: '/dual-worlds'
      preLoaderRoute: typeof DualWorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/from-javascript': {
      id: '/from-javascript'
      path: '/from-javascript'
      fullPath: '/from-javascript'
      preLoaderRoute: typeof FromJavascriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/from-systems': {
      id: '/from-systems'
      path: '/from-systems'
      fullPath: '/from-systems'
      preLoaderRoute: typeof FromSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-io': {
      id: '/host-io'
      path: '/host-io'
      fullPath: '/host-io'
      preLoaderRoute: typeof HostIoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/native-types': {
      id: '/native-types'
      path: '/native-types'
      fullPath: '/native-types'
      preLoaderRoute: typeof NativeTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference-host-io': {
      id: '/reference-host-io'
      path: '/reference-host-io'
      fullPath: '/reference-host-io'
      preLoaderRoute: typeof ReferenceHostIoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference-packages': {
      id: '/reference-packages'
      path: '/reference-packages'
      fullPath: '/reference-packages'
      preLoaderRoute: typeof ReferencePackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types': {
      id: '/types'
      path: '/types'
      fullPath: '/types'
      preLoaderRoute: typeof TypesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliRoute: CliRoute,
  DualWorldRulesRoute: DualWorldRulesRoute,
  DualWorldsRoute: DualWorldsRoute,
  FromJavascriptRoute: FromJavascriptRoute,
  FromSystemsRoute: FromSystemsRoute,
  HostIoRoute: HostIoRoute,
  InstallRoute: InstallRoute,
  LearnRoute: LearnRoute,
  ModulesRoute: ModulesRoute,
  NativeTypesRoute: NativeTypesRoute,
  PackagesRoute: PackagesRoute,
  ReferenceRoute: ReferenceRoute,
  ReferenceHostIoRoute: ReferenceHostIoRoute,
  ReferencePackagesRoute: ReferencePackagesRoute,
  TypesRoute: TypesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
